import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    marginBottom: 20,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
  },
  
  // Botón flotante
  floatingButton: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    flex: 1,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  formContainer: {
    flex: 1,
    padding: 20,
  },

  // Campos del formulario
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    fontSize: 16,
  },
  textArea: {
    minHeight: 100,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
  },

  // Campo de búsqueda para categorías/comunas
  searchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    position: 'relative',
  },
  searchInput: {
    flex: 1,
    height: 42,
    borderWidth: 1,
    borderRadius: 8,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 15,
  },
  searchIconSmall: {
    position: 'absolute',
    left: 12,
    zIndex: 1,
  },
  clearButton: {
    position: 'absolute',
    right: 12,
    zIndex: 1,
    padding: 4,
  },

  // Selector de categorías/comunas (chips)
  pickerContainer: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
  },
  categoryChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#E0E0E0',
    marginRight: 10,
  },
  categoryChipText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  emptyChips: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderWidth: 1,
    borderRadius: 10,
    gap: 8,
  },
  emptyChipsText: {
    fontSize: 13,
    flex: 1,
  },
  loadingCatalogos: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
  },

  // Búsqueda de dirección con autocompletado
  busquedaContainer: {
    position: 'relative',
    zIndex: 1000,
  },
  busquedaInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  inputBusqueda: {
    flex: 1,
    height: 50,
    borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 45,
    paddingRight: 45,
    fontSize: 16,
  },
  searchIcon: {
    position: 'absolute',
    left: 15,
    zIndex: 1,
  },
  searchLoader: {
    position: 'absolute',
    right: 15,
    zIndex: 1,
  },
  sugerenciasContainer: {
    marginTop: 8,
    borderWidth: 1,
    borderRadius: 10,
    maxHeight: 200,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  sugerenciasList: {
    maxHeight: 200,
  },
  sugerenciaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    gap: 12,
  },
  sugerenciaDireccion: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
  },
  noResultados: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderRadius: 10,
    gap: 8,
  },
  noResultadosTexto: {
    fontSize: 13,
    flex: 1,
  },
  direccionSeleccionada: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    marginTop: 8,
    borderWidth: 1.5,
    borderRadius: 8,
    gap: 8,
  },
  ubicacionConfirmada: {
    fontSize: 13,
    fontWeight: '600',
  },

  // Date picker
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    gap: 10,
  },
  dateButtonText: {
    fontSize: 16,
  },

  // Botones del formulario
  buttonContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  button: {
    flex: 1,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButton: {
    borderWidth: 1,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  submitButton: {
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  submitButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },

  // Lista de solicitudes
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  emptySubtext: {
    marginTop: 8,
    fontSize: 14,
  },
  solicitudesList: {
    paddingBottom: 20,
  },

  // Tarjeta de solicitud - Diseño profesional
  solicitudCard: {
    marginTop: 15,
    marginHorizontal: 2,
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 18,
    paddingBottom: 14,
    gap: 12,
  },
  cardTitleContainer: {
    flex: 1,
    marginRight: 8,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    letterSpacing: -0.3,
  },
  estadoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    gap: 6,
  },
  estadoDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  estadoText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  cardTagsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 18,
    paddingBottom: 14,
    gap: 8,
    flexWrap: 'wrap',
  },
  cardTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  cardTagText: {
    fontSize: 12,
    fontWeight: '500',
  },
  cardDescriptionSection: {
    paddingHorizontal: 18,
    paddingBottom: 16,
  },
  cardDescription: {
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '400',
  },
  cardInfoSection: {
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 18,
    marginBottom: 16,
    gap: 12,
  },
  cardInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cardInfoIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardInfoText: {
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
    lineHeight: 18,
  },
  cardFooter: {
    paddingHorizontal: 15,
    paddingBottom: 12,
    paddingTop: 10,
  },
  fechaInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  fechaText: {
    fontSize: 12,
    lineHeight: 16,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  cardActions: {
    flexDirection: 'row',
    borderTopWidth: 1,
  },
  verDetalleButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    flex: 1,
    gap: 6,
  },
  verDetalleText: {
    fontSize: 14,
    fontWeight: '600',
  },
  verOfertasButtonCard: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    flex: 1,
    borderTopWidth: 1,
    gap: 6,
  },
  verOfertasTextCard: {
    fontSize: 14,
    fontWeight: '600',
  },

  // Modal de Detalle
  modalDetalleContent: {
    height: height * 0.85,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  detalleContainer: {
    flex: 1,
    paddingTop: 20,
  },
  detalleTituloContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  detalleTituloHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 12,
  },
  detalleTitulo: {
    flex: 1,
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 32,
  },
  detalleEstadoBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    gap: 6,
  },
  estadoDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  detalleEstadoTextCompact: {
    fontSize: 13,
    fontWeight: '600',
  },
  detalleCategoriaComuna: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detalleCategoriaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  detalleCategoriaTexto: {
    fontSize: 13,
    fontWeight: '500',
  },
  detalleSeparador: {
    fontSize: 12,
  },
  detalleDivisor: {
    height: 1,
    marginBottom: 20,
  },
  detalleSection: {
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  detalleSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  detalleSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  detalleTexto: {
    fontSize: 15,
    lineHeight: 22,
  },
  detalleRow: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  detalleRowItem: {
    flex: 1,
  },
  coordenadasContainer: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  coordenadasTexto: {
    fontSize: 12,
    fontFamily: 'monospace',
  },
  detalleFechasContainer: {
    gap: 12,
  },
  detalleFechaItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detalleFechaLabel: {
    fontSize: 13,
    fontWeight: '500',
  },
  detalleFechaValor: {
    fontSize: 13,
    fontWeight: '600',
  },
  detalleFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    padding: 15,
    gap: 10,
    borderTopWidth: 1,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  detalleButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 10,
    gap: 8,
  },
  cancelarButton: {
    borderWidth: 1,
    borderColor: '#C62828',
  },
  renovarButton: {
    borderWidth: 1,
    borderColor: '#2E7D32',
  },
  verOfertasButton: {
    // Estilo para el botón de ver ofertas
  },
  detalleButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },

  // Estilos para ofertas en modal de solicitud
  ofertasModalHeader: {
    padding: 20,
    borderBottomWidth: 1,
  },
  ofertasModalTitulo: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 4,
  },
  ofertasModalSubtitle: {
    fontSize: 14,
  },
  ofertaCardSolicitud: {
    marginHorizontal: 20,
    marginTop: 15,
    marginBottom: 10,
    borderRadius: 16,
    borderWidth: 1,
    padding: 0,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  ofertaCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  ofertaCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  ofertaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    gap: 6,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  ofertaBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFF',
    letterSpacing: 0.5,
  },
  ofertaFechaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.03)',
  },
  ofertaFechaText: {
    fontSize: 12,
    fontWeight: '600',
  },
  proveedorContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 18,
    marginTop: 14,
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
  },
  proveedorInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  proveedorNombre: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
  },
  verPerfilText: {
    fontSize: 13,
    fontWeight: '500',
  },
  calificacionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
  },
  calificacionContainerSeparada: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1.5,
    marginHorizontal: 18,
    marginBottom: 14,
    alignSelf: 'flex-start',
    elevation: 1,
    shadowColor: '#FFB300',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  calificacionText: {
    fontSize: 15,
    fontWeight: '700',
  },
  montoContainer: {
    marginHorizontal: 18,
    marginBottom: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.02)',
  },
  montoLabel: {
    fontSize: 12,
    marginBottom: 6,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  montoValue: {
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: -0.5,
  },
  comentarioContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginHorizontal: 18,
    marginBottom: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.02)',
    gap: 10,
  },
  comentarioText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  ofertasList: {
    paddingBottom: 100, // Espacio extra para que el botón de cerrar no tape el contenido
    paddingTop: 10,
  },
  ofertaCardActions: {
    flexDirection: 'row',
    marginTop: 4,
    paddingTop: 18,
    paddingBottom: 18,
    paddingHorizontal: 18,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    gap: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.01)',
  },
  rechazarButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#FFEBEE',
    gap: 8,
    elevation: 2,
    shadowColor: '#C62828',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  rechazarButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#C62828',
    letterSpacing: 0.3,
  },
  aceptarButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  aceptarButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFF',
    letterSpacing: 0.3,
  },

  // Estilos para selección de imágenes
  imageLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  imageCountBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  imageCountText: {
    fontSize: 12,
    fontWeight: '700',
  },
  imageContainer: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 100,
  },
  imagesListContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 12,
  },
  imagePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderRadius: 12,
    padding: 20,
    gap: 10,
  },
  imagePickerText: {
    fontSize: 16,
    fontWeight: '500',
  },
  imagePreviewContainer: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    width: '48%',
    marginBottom: 8,
  },
  imagePreview: {
    width: '100%',
    height: 150,
  },
  removeImageButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    padding: 4,
    zIndex: 1,
  },
  imageName: {
    padding: 6,
    fontSize: 11,
    textAlign: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
  },
  imageLoadingText: {
    marginTop: 8,
    fontSize: 14,
  },
  imageHelperText: {
    marginTop: 8,
    fontSize: 12,
    fontStyle: 'italic',
  },

  // Estilos para imágenes en el detalle de solicitud
  detalleImagesContainer: {
    paddingVertical: 8,
    gap: 12,
  },
  detalleImageWrapper: {
    width: 200,
    height: 150,
    borderRadius: 12,
    overflow: 'hidden',
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  detalleImage: {
    width: '100%',
    height: '100%',
  },

  // Estilos para modal de imagen completa
  modalImagenCompletaOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalImagenCompletaCloseButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
    padding: 8,
  },
  modalImagenCompleta: {
    width: '100%',
    height: '100%',
  },

  // Estilos para filtros de estado
  filtrosContainer: {
    marginBottom: 12,
  },
  filtroSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
  },
  filtroSelectorContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  filtroSelectorText: {
    fontSize: 15,
    fontWeight: '500',
  },
  modalSelectorContent: {
    marginHorizontal: 20,
    marginTop: 'auto',
    marginBottom: 'auto',
    borderRadius: 16,
    maxHeight: '70%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalSelectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
  },
  modalSelectorTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  estadoSelectorList: {
    maxHeight: 400,
  },
  estadoSelectorItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  estadoSelectorText: {
    fontSize: 16,
  },

  // Estilos para perfil de usuario modal
  perfilUsuarioHeaderCard: {
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 20,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 24,
    borderRadius: 16,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  perfilUsuarioHeader: {
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  perfilUsuarioAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 16,
    borderWidth: 4,
    borderColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  perfilUsuarioAvatarPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 4,
    borderColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  perfilUsuarioAvatarText: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#fff',
  },
  perfilUsuarioNombre: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  profesionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    gap: 6,
  },
  profesionBadgeText: {
    fontSize: 14,
    fontWeight: '600',
  },
  perfilSeccionTitulo: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
    marginTop: 8,
  },
  perfilCalificacionesGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  perfilCalificacionCard: {
    flex: 1,
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  perfilCalificacionIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  perfilCalificacionLabel: {
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 8,
    textAlign: 'center',
  },
  perfilCalificacionValor: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  perfilCalificacionNumero: {
    fontSize: 24,
    fontWeight: '700',
  },
  perfilUsuarioEmail: {
    fontSize: 14,
  },
  perfilUsuarioInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
  },
  perfilUsuarioInfoLabel: {
    fontSize: 15,
    flex: 1,
  },
  perfilUsuarioInfoText: {
    fontSize: 15,
  },
  perfilUsuarioCalificacion: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  perfilEstadisticaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    gap: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  perfilEstadisticaIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  perfilEstadisticaContent: {
    flex: 1,
  },
  perfilEstadisticaLabel: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 4,
  },
  perfilEstadisticaValor: {
    fontSize: 32,
    fontWeight: '700',
  },
  perfilBiografiaCard: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 8,
  },
});
